### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [luratic/LinkedInConversion#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on pid and data.conversionId  when generating the url
var trackingUrl = 'https://px.ads.linkedin.com/collect/?pid=' + pid + '&conversionId=' + data.conversionId + '&fmt=gif&cb=' + getTimestamp();

**Comment by luratic-devs** [comment]
Many thanks  @praveena-pappu :)
